definitions:
  models.User:
    properties:
      email:
        type: string
      group_name:
        type: string
      name:
        maxLength: 255
        minLength: 3
        type: string
    required:
    - email
    - name
    type: object
info:
  contact: {}
paths:
  /accounts/{id}:
    get:
      consumes:
      - application/json
      description: get all account of user
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: get accounts
      tags:
      - accounts
swagger: "2.0"
